name: estagioapp
description: Aplicativo para facilitar acesso a documentação de estágio

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  path_provider: ^2.0.14
  google_fonts: ^4.0.3
  permission_handler: ^10.2.0
  open_file_safe: any



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/rocket.png
    - assets/nuvens.png
    - assets/morty.gif
    - assets/metroid.gif
    - assets/ashoka.gif
    - assets/megaman2.gif
    - assets/darth.gif
    - assets/goku.gif
    - assets/jedi.gif
    - assets/mario.gif
    - assets/rogue.gif
    - assets/tale2.gif
    - assets/thor2.gif
    - assets/venom.gif
    - assets/zero2.gif
    - assets/storm.gif
    - assets/spiderman.gif
    - assets/sonic2.gif
    - assets/mario2.gif
    - assets/ryu.gif
    - assets/tale2.gif
    - assets/pokebola.gif
    - assets/start.gif
    - assets/botao.gif
    - assets/titulo.gif
    - assets/botao03.gif
    - assets/botao04.gif
    - assets/botao05.gif
    - assets/titulo.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
